version: "3"


services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ../withRest:/app
    command: >
      gunicorn withRest.wsgi:application --bind 0.0.0.0:8000 --workers 3